### PR TITLE
Refactor handleNotifications + solve bug

### PR DESCRIPTION
**Pull request by mavaras**
### Description
Refactors `handleNotifications` and solves a bug that was causing an issue when adding/updating/deleting notifications in a IR resource previously created with no notifications within it.

### How has this been tested?
Whole functionality tested by deploying the operator to an Openshift cluster and using a test Quay organization to play with ImageRepository's notifications by testing all the functional workflows.

---
JIRA: [ISV-5058](https://issues.redhat.com/browse/ISV-5058)

### CODE REVIEW

**Comment by MartinBasti** [comment]
Can you please add description also to commit, not just PR

**Review by mmorhun — APPROVED** [review]

**Review by mmorhun — APPROVED** [review]

**Pull request merged**
